[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
program = "BV7ScLttfAjpFG1GcgLJUi1kCW6Kd4iSDUabvdno2Bkv"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
