[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
harvester = "AujdsDt1vs3RZ497KhoPxzKeRFghdEbjNKVqYSypEP1W"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
